name             'salad'
maintainer       'Markus Klepp'
maintainer_email 'khor@entwicklerbier.org'
license          'The MIT License (MIT)'
description      'Installs/Configures salad'
long_description 'Installs/Configures salad'
version          '0.1.0'
